### ISSUE TITLE
VB6 calls the NIm-generated DLL (sorry but I didn't find another concact)

### ISSUE THREAD

**Issue by rubgithub** [yuekcc/build_scripts#1]
Hi there, I've read your blog at https://my.oschina.net/yuekcc/blog/775990 and tried to reproduce but without success.

Could you please provide an example Using Nim to Creating a vb6 dll that Returns String? 
I've tried to reproduce you exemple but without success.

I'm using `Nim Compiler Version 1.6.6 [Windows: i386]`

I created questions about this issue, you can find they here:
https://stackoverflow.com/questions/72952227/using-nim-to-creating-a-vb6-dll-that-returns-string
https://forum.nim-lang.org/t/9298

**Comment by yuekcc** [comment]
I read the post in StackOverflow. It seems a symbol issue. The `return_multiply@8` was not exists in your DLL. the `@8` postfix maybe add by nim compiler, but just in old version of nim. 

I run the demo code nim 1.6.6, and then use `objdump` search for symbol.

```sh
# run in git bash
objdump.exe -t lib.dll  | grep return_multiply
[276](sec  1)(fl 0x00)(ty   20)(scl   2) (nx 0) 0x000000000000e9d0 return_multiply
```

>In windows you can use  [dependency walker](http://dependencywalker.com/) to find out symbols table, as i wrote in my post. But this program seems not work in my windows 10 pc.

there is no `@8` postfix any more. i think that is the answer. __maybe it had fixed by new version of nim, or depends on architecture of you pc__. For now, I'm using a AMD64 pc.

there is no vb6 in my pc. I use python3.9 for testing the DLL:

```py
import ctypes

# import the stdcall dll
lib = ctypes.windll.LoadLibrary('./lib.dll')
print(lib.return_multiply(1, 2)) # => 2
``` 

nim code is the same as that post:

```nim
# dll.nim
proc return_multiply*(a, b: int): int {.stdcall, exportc, dynlib.} =
    a * b

```

build: 

```sh
nim c -d:release --app:lib --nomain dll.nim
```

I'm not use vb6 and nim for several years. I hope it can help.

**Comment by rubgithub** [comment]
Thanks for your attetion, `return_multiply` it is working fine, my problem is returning string.

```
proc fromVBString*(a: VBString): string =
    return encodings.convert($a, "UTF-8", vbCodePage)
```


> there is no vb6 in my pc. I use python3.9 for testing the DLL:


Can you provide a sample with python returning string?

**Comment by yuekcc** [comment]
i have some sample here.

the __dll.nim__:

```nim
import std/strutils

proc return_multiply*(a, b: int): int {.stdcall, exportc, dynlib.} =
    a * b

proc repeat_str*(str: cstring, times: int): cstring {.stdcall, exportc, dynlib.} =
    ($str).repeat(times)

```

you may use this command for build a dll:

```sh
nim c --app:lib --mm:arc --nomain -d:release lib.nim
```

`--mm:arc` is the option for using the `ARC` gc. rather then the default `refc` gc.

the __call_dll.py__:
```py
from ctypes import *

lib = windll.LoadLibrary('./lib.dll')

lib.return_multiply.argtypes = [c_int, c_int]
lib.return_multiply.restype = c_int

lib.repeat_str.argtypes = [c_char_p, c_int]
lib.repeat_str.restype = c_char_p

def return_multiply(a, b):
    return lib.return_multiply(a, b)

def repeat_str(word, times):
    res = lib.repeat_str(word.encode(), 5)
    return res.decode()

print(return_multiply(1, 2)) # => 2
print(repeat_str('hello ', 5)) # => hello hello hello hello hello

```

it works well with ascii, but not for the utf-8 text. 

i think you should search  something like utf-8 encode/deconde or read more about nim.

PS. this nim code may not work with vb6.

**Comment by rubgithub** [comment]
Thank you.
